datasources:
- name: Prometheus
  access: proxy
  type: prometheus
  url: http://prometheus:9090
  isDefault: true


- name: Loki
  type: loki
  access: proxy
  url: http://localhost:3100/metrics
  jsonData:
    maxLines: 1000 